.travis.yml
README.md

feedback build status and fix build (partition size)

Build feedback

---

app_httpd.cpp
camera_index_ov2640.h
camera_index_ov3660.h
camera_pins.h
esp32-cam-webserver.ino
myconfig.sample.h

Tested and good to go once Travis is finished

Moreconfig

---

camera_pins.h
esp32-cam-webserver.ino
myconfig.sample.h

Removecameraselector

---

app_httpd.cpp
camera_pins.h
myconfig.sample.h

Tested on my demo board, two new board models added and a minor code change were the only differences.

fix #15 Synced against board and app updates in upstream

---

app_httpd.cpp
camera_index_ov2640.h
camera_index_ov3660.h
miniviewer.h

Less cluttered viewer that does not expose all the camera controls.
Just the resolution and Lamp level.

Mini viewer

---

app_httpd.cpp
camera_index_ov2640.h
camera_index_ov3660.h
css.h
index_ov2640.h
index_ov3660.h
miniviewer.h

Saves a bit of memory; makes skinning and theming the site easier.

move css into include file, and reduce whitespace in hosted site.

---

app_httpd.cpp
css.h
index_ov2640.h
index_ov3660.h
viewers.h

separate dedicated view for stream

Streamviewer

---

esp32-cam-webserver.ino
myconfig.sample.h

Wifi persistance

---

.travis.yml

nice bonus; also tests non AP-mode builds

Build default, then with myconfig, 

---

.travis.yml
platformio.ini

Add platformio to travis CI build

PlatformIO travis

---

app_httpd.cpp
esp32-cam-webserver.ino
myconfig.sample.h

You can now supply ssid/password pairs for multiple networks; the strongest matching network will be connected. Disconnect/failover works properly. Static setting can be optionally applied, 
AccessPoint mode can be configured as a default, or a optional fallback if no known networks found. a basic captive portal (dns redirect) can be configured for it.

Multi wifi

---

app_httpd.cpp
esp32-cam-webserver.ino
src/version.h

Add a simple upstream versioning system, string reported in startup console + dump output. Fix #67 
With the ArduinoIDE this is about as far as it can be automated.. but should assist in debugging user issues etc.

Simple versioning system

---

API.md
CONTRIBUTING.md
README.md
esp32-cam-webserver.ino
myconfig.sample.h

Api and other documentation

---

.travis.yml

.......ffs
Dear Travis. Python2 died 3 months ago and good riddance.. 
please try to keep up.

Fix travis py3

---

app_httpd.cpp
esp32-cam-webserver.ino

Get the debug toggle working in both Station and AP mode

Debug Toggle in AP mode

---

app_httpd.cpp

face detect fix

---

app_httpd.cpp
src/version.h

Free boxes

---

app_httpd.cpp
esp32-cam-webserver.ino
myconfig.sample.h

Useful going forward, but at present only displays in dump screens
Resolves #38

NTP basic sync

---

src/jsonlib/jsonlib.cpp

Fixes compiling with ESP IDE2.0.0 alpha
Initial testing reveals no problem with the resulting build, all web, wifi and stream features appear to work correctly.

Fix compiling for ESP Arduino core 2.x

---

src/jsonlib/jsonlib.cpp

Includes a off-by-one error fix that seems relevant.

Import latest fixes from upstream jsonlib

---

app_httpd.cpp
esp32-cam-webserver.ino

Give the MCU temperature; fixes #151
Also show the OTA status and password on serial (but not on the dump page for security reasons)

Temperature and OTA feedback

---

esp32-cam-webserver.ino
index_other.h

\n\r gives strange results in other than Arduino serial monitors.

replaced \n\r with \r\n

---

README.md
esp32-cam-webserver.ino
myconfig.sample.h

Here are the additions for MDNS support. Thanks!

Mdns additions
